data:
  seed: 42
  version: v1+v2+v3
model:
  conv_filters: 32
  kernel_size: 3
  lr: 0.001
  num_conv_layers: 2
split:
  test: 0.15
  train: 0.7
  val: 0.15
tuning:
  conv_filters_options:
  - 16
  - 32
  - 64
  lr_options:
  - 0.001
  - 0.0005
  - 0.0001
